name: CI

on: [push]

jobs:
  package-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.13'
      - name: Install package
        uses: npm install
      - name: Run package check
        uses: npm audit --audit-level=critical
